export const STRINGS = {
  app: {
    title: "Portfolio Risk & Exposure Service",
    description: "Service for calculating risk and exposure of investment portfolios.",
  },
  dashboard: {
    title: "Dashboard",
    activePortfolioSingular: "active portfolio",
    activePortfolioPlural: "active portfolios",
    searchPlaceholder: "Search portfolios...",
    openBreachSingular: "open breach",
    openBreachPlural: "open breaches",
  },
  alerts: {
    title: "Alerts",
    none: "No open breaches - all clear.",
    viewAll: "View All Breaches",
    view: "View",
    excess: "Excess",
  },
  breaches: {
    title: "Breach Management",
    tabBreaches: "Breaches",
    tabAccepted: "Accepted",
    breachSingular: "breach",
    breachPlural: "breaches",
    acceptButton: "Accept",
    acceptedButton: "Accepted",
    openBreachSingular: "open breach",
    openBreachPlural: "open breaches",
    acceptedBreachSingular: "accepted breach",
    acceptedBreachPlural: "accepted breaches",
    noOpenBreaches: "No open breaches. Great job!",
    noAcceptedBreaches: "No accepted breaches yet.",
    failedToAccept: "Failed to accept breach",
  },
  portfolioTypes: {
    equity: "Equity",
    fixedIncome: "Fixed Income",
    multiAsset: "Multi-Asset",
    hedge: "Hedge",
    moneyMarket: "Money Market",
  },
  portfolioCard: {
    aum: "AUM",
    currency: "Currency",
    breachesSingular: "Breach",
    breachesPlural: "Breaches",
  },
  portfolioOverview: {
    title: "Portfolio overview",
    backToOverview: "Back to dashboard",
    managedBy: "Managed by",
    details: {
      aum: "AUM",
      baseCurrency: "Base currency",
      positionsCount: "Positions",
      benchmark: "Benchmark",
    },
    stats: {
      title: "Risk snapshot",
      exposure: "Exposure",
      var1Day: "1-day VaR",
      limitsCount: "Limits",
      limitsTitle: "Limit utilisation",
      breachedLimits: "Breached limits",
      bySector: "Exposure by sector",
      byAsset: "Exposure by asset",
      sector: "Sector",
      limitType: "Limit type",
      currentValue: "Current value",
      limitValue: "Limit value",
      utilisation: "Utilisation",
      status: "Status",
      share: "Share",
      empty: "No data available.",
    },
    positions: {
      title: "Positions",
      searchPlaceholder: "Search positions...",
      showing: "Showing",
      of: "of",
      suffix: "positions",
      empty: "No positions match your search.",
    },
    instrumentDetails: {
      tabTitle: "Instrument details",
      selectedPosition: "Selected position",
    },
    labels: {
      instrumentId: "Instrument ID",
      isin: "ISIN",
      issuer: "Issuer",
      assetClass: "Asset class",
      sector: "Sector",
      currency: "Currency",
      quantity: "Quantity",
      marketPrice: "Market price",
      marketValue: "Market value",
      weight: "Weight",
    },
    table: {
      instrument: "Instrument",
      isin: "ISIN",
      assetClass: "Asset class",
      weight: "Weight",
      marketValue: "Market value",
    },
    fallback: {
      unknown: "—",
    },
  },
  errors: {
    backendUnreachableTitle: "Backend Unreachable",
    dataUnavailableTitle: "Data Unavailable",
    backendUnreachableMessage:
      "The backend could not be reached.",
    dataUnavailableMessage: "An error occurred while loading portfolio data.",
    tryAgain: "Try again",
  },
  api: {
    backendUnreachablePrefix: "Could not reach the backend",
    backendReturnedPrefix: "Backend returned",
    backendRunningQuestion: "Is the server running?",
  },
} as const;
