name: Build and Push Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set lowercase repository name
        run: echo "GH_REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push [BACKEND] image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.GH_REPO_LC }}/backend:${{ github.sha }},
                ghcr.io/${{ env.GH_REPO_LC }}/backend:latest
        
      - name: Build and push [FRONTEND] image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ env.GH_REPO_LC }}/frontend:${{ github.sha }},
                ghcr.io/${{ env.GH_REPO_LC }}/frontend:latest
